import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

const url = 'https://www.usacoincollector.com/collector-education/2026-trump-dollar-july-4-privy-mark';
const title = '2026 Trump $1 Coin July 4th Privy Mark Guide | USA Coin Collector';
const description = 'Learn how to identify the July 4th privy mark on the 2026 Trump $1 coin, how many were produced, where to look for the mark, and the correct holder size.';

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: url },
  openGraph: { title, description, url, type: 'article', publishedTime: '2026-09-03T00:00:00Z', modifiedTime: '2026-09-04T00:00:00Z', siteName: 'USA Coin Collector' },
  twitter: { card: 'summary_large_image', title, description },
  robots: { index: true, follow: true }
};

const sources = [
  ['U.S. Mint: Donald Trump Coin', 'https://www.usmint.gov/campaigns/donald-trump-coin'],
  ['U.S. Mint press release: rolls and bags available September 2', 'https://www.usmint.gov/news/press-releases/2026-semiquincentennial-president-donald-j-trump-one-dollar-coin-rolls-and-bags-available-september-2'],
  ['U.S. Mint product page: 2026 Trump $1 coin rolls and bags', 'https://www.usmint.gov/semiquincentennial-president-donald-j-trump-2026-1-coin-rolls-bags-MASTER_SEMIQDJT.html'],
  ['U.S. Mint Semiquincentennial media resources', 'https://www.usmint.gov/news/media-kit/semiq-resources']
];

export default function TrumpDollarGuidePage() {
  const articleJsonLd = { '@context': 'https://schema.org', '@type': 'Article', headline: '2026 Trump $1 Coin: How to Identify the July 4th Privy Mark & Protect Your Coin', description, datePublished: '2026-09-03', dateModified: '2026-09-04', author: { '@type': 'Organization', name: 'USA Coin Collector' }, publisher: { '@type': 'Organization', name: 'USA Coin Collector', url: 'https://www.usacoincollector.com' }, mainEntityOfPage: url };
  const breadcrumbJsonLd = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.usacoincollector.com/' }, { '@type': 'ListItem', position: 2, name: 'Collector Education', item: 'https://www.usacoincollector.com/collector-education' }, { '@type': 'ListItem', position: 3, name: '2026 Trump $1 Coin Guide', item: url }] };
  return <article className="mx-auto max-w-4xl space-y-10">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
    <nav aria-label="Breadcrumb" className="text-sm text-slate-600"><Link href="/">Home</Link> / <Link href="/collector-education">Collector Education</Link> / 2026 Trump $1 Coin</nav>
    <header className="rounded-lg border border-slate-200 bg-white p-7 shadow-sm md:p-10"><p className="text-sm font-bold uppercase tracking-[0.2em] text-slate-500">2026 Coin Guide</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-[#b91c1c] md:text-5xl">2026 Trump $1 Coin: How to Identify the July 4th Privy Mark &amp; Protect Your Coin</h1><p className="mt-5 text-lg leading-8 text-slate-700">The U.S. Mint released rolls and bags of the 2026 Semiquincentennial President Donald J. Trump $1 Coin on September 2, 2026. A limited number have a small July 4th privy mark on the obverse. Here is how to tell the two versions apart.</p><p className="mt-5 text-sm text-slate-500"><time dateTime="2026-09-03">Published September 3, 2026</time> · <time dateTime="2026-09-04">Updated September 4, 2026</time> · USA Coin Collector</p></header>

    <aside className="rounded-lg border-l-4 border-[#c89e28] bg-white p-6 shadow-sm" aria-labelledby="quick-answer"><h2 id="quick-answer" className="text-2xl font-bold">Quick answer</h2><p className="mt-3 leading-7 text-slate-700">Check the heads (obverse) side, in the open field to the left of the portrait and immediately above the five-pointed star near the lower-left edge. The special mark reads <strong>JULY / 4th</strong> on two small lines. The large “250” on the reverse shield is part of every coin’s regular design—not the privy mark.</p></aside>

    <section><h2 className="text-3xl font-bold text-slate-950">What Is the 2026 Trump $1 Coin?</h2><p className="mt-4 leading-8 text-slate-700">This noncirculating numismatic dollar commemorates the United States Semiquincentennial. The Philadelphia Mint struck the normal version with a circulating finish, no mint mark, and a plain edge. Its obverse shows Donald J. Trump with “LIBERTY,” “IN GOD WE TRUST,” and the dual date “1776 ~ 2026.” The reverse shows the Presidential Seal with “250,” “UNITED STATES OF AMERICA,” and “ONE DOLLAR.”</p></section>
    <section><h2 className="text-3xl font-bold text-slate-950">What Is the July 4th Privy-Mark Version?</h2><p className="mt-4 leading-8 text-slate-700">The U.S. Mint says it struck 250,000 coins on July 4, 2026 with a special “July 4th” privy mark, then randomly placed those coins in Mint rolls and bags. The privy identifies this subset; it does not change the coin’s denomination or specifications.</p></section>

    <section id="identify-privy-mark"><h2 className="text-3xl font-bold text-slate-950">How to Identify the July 4th Privy Mark</h2><div className="mt-6 grid gap-6 rounded-lg border border-slate-200 bg-white p-6 md:grid-cols-[0.9fr_1.1fr] md:items-center"><figure><Image alt="Obverse of the 2026 Trump dollar with the July 4th privy mark circled to the left of the portrait" className="h-auto w-full" height={470} sizes="(min-width: 768px) 340px, 100vw" src="/trump_privy.png" width={458} priority/><figcaption className="mt-3 text-center text-sm font-semibold text-slate-600">The July 4th privy mark appears to the left of the portrait, immediately above the lower-left star.</figcaption></figure><div><h3 className="text-xl font-bold">What to look for</h3><ul className="mt-4 list-disc space-y-2 pl-5 leading-7 text-slate-700"><li>Look at the heads/obverse side.</li><li>Look to the left of Trump&apos;s portrait.</li><li>Check immediately above the lower-left star.</li><li>Look for the small two-line “JULY / 4th” marking.</li><li>Do not confuse it with the “250” on the reverse.</li></ul></div></div></section>

    <section><h2 className="text-3xl font-bold text-slate-950">Standard Coin vs. July 4th Privy Version</h2><div className="mt-5 overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-left"><thead className="bg-slate-50"><tr><th className="p-4">Feature</th><th className="p-4">Standard 2026 Trump $1 Coin</th><th className="p-4">July 4th Privy Mark Version</th></tr></thead><tbody><tr className="border-t"><th className="p-4">Obverse field</th><td className="p-4">No privy mark</td><td className="p-4">Small “JULY / 4th” mark left of the portrait</td></tr><tr className="border-t"><th className="p-4">Reverse “250”</th><td className="p-4">Present</td><td className="p-4">Present</td></tr><tr className="border-t"><th className="p-4">Distribution</th><td className="p-4">Mint rolls and bags</td><td className="p-4">Randomly included in Mint rolls and bags</td></tr></tbody></table></div></section>
    <section><h2 className="text-3xl font-bold text-slate-950">Where Were the Privy Coins Released?</h2><p className="mt-4 leading-8 text-slate-700">The Mint did not sell the privy coins as a separately identified product. It says the 250,000 marked pieces were randomly mixed into the rolls and bags that went on sale September 2. Finding one therefore requires inspecting coins from those products rather than relying on package labeling.</p></section>
    <section><h2 className="text-3xl font-bold text-slate-950">Is the July 4th Privy Mark Trump Dollar Rare or Valuable?</h2><p className="mt-4 leading-8 text-slate-700">A production total of 250,000 makes the marked issue considerably more limited than the overall Trump-dollar release. That fact alone does not establish a fixed resale value. Prices for a new issue can change quickly, and condition, certified grade, collector demand, and completed market sales may all affect what a buyer pays. Treat early asking prices as asking prices—not proof of value.</p></section>
    <section><h2 className="text-3xl font-bold text-slate-950">Coin Specifications</h2><div className="mt-5 overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-left"><tbody>{[['Denomination','$1'],['Mint','Philadelphia (no mint mark)'],['Diameter','26.49 mm / 1.043 inches'],['Weight','8.10 grams'],['Thickness','2.00 mm'],['Edge','Plain'],['Finish','Circulating'],['Composition','6% zinc, 3.5% manganese, 2% nickel, balance copper']].map(([label,value]) => <tr className="border-t first:border-0" key={label}><th className="w-1/3 bg-slate-50 p-4">{label}</th><td className="p-4">{value}</td></tr>)}</tbody></table></div></section>
    <section><h2 className="text-3xl font-bold text-slate-950">How to Protect a 2026 Trump $1 Coin</h2><p className="mt-4 leading-8 text-slate-700">Hold the coin only by its edges, do not clean it, and avoid storage containing PVC. Fingerprints and friction can permanently affect higher-condition examples. At 26.49 mm, this coin fits the <Link className="font-semibold text-[#a47d13] underline" href="/sizing-guide#2026-trump-dollar">Coin Shield Small Dollar 26.49 mm holder</Link>. You can also view the <a className="font-semibold text-[#a47d13] underline" href="https://www.amazon.com/2x2-Premium-Cardboard-Coin-Archival/dp/B0DGDS52GJ/" rel="noreferrer sponsored" target="_blank">2x2 Small Dollar cardboard coin holder in the Coin Shield Amazon store</a>.</p></section>
    <section><h2 className="text-3xl font-bold text-slate-950">Frequently Asked Questions</h2><div className="mt-5 space-y-3"><details className="rounded-lg border bg-white p-5" open><summary className="font-bold">Where is the Trump dollar privy mark?</summary><p className="mt-3 leading-7 text-slate-700">It is on the obverse, left of the portrait and above the five-pointed star near the lower-left portion of the coin.</p></details><details className="rounded-lg border bg-white p-5"><summary className="font-bold">Is the “250” the July 4th privy mark?</summary><p className="mt-3 leading-7 text-slate-700">No. “250” is part of the normal reverse design. The special mark is the small two-line “JULY / 4th” on the obverse.</p></details><details className="rounded-lg border bg-white p-5"><summary className="font-bold">How many July 4th privy coins were made?</summary><p className="mt-3 leading-7 text-slate-700">The U.S. Mint reports a production total of 250,000.</p></details><details className="rounded-lg border bg-white p-5"><summary className="font-bold">What holder fits the 2026 Trump dollar?</summary><p className="mt-3 leading-7 text-slate-700">Its 26.49 mm diameter corresponds to a Small Dollar 26.49 mm holder.</p></details></div></section>
    <section><h2 className="text-3xl font-bold text-slate-950">Sources</h2><p className="mt-3 leading-7 text-slate-600">Facts were checked against official U.S. Mint materials on September 4, 2026. Product availability and collector-market conditions may change.</p><ul className="mt-4 list-disc space-y-2 pl-5">{sources.map(([label,href]) => <li key={href}><a className="text-[#102a63] underline" href={href} rel="noreferrer" target="_blank">{label}</a></li>)}</ul></section>
  </article>;
}
